import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import path from 'node:path'
import { execSync } from 'node:child_process'

// When deploying to https://<USER>.github.io/<REPO>/, set BASE_PATH=/<REPO>/
// Locally, leave unset.
const base = process.env.BASE_PATH ?? '/'

// Resolve the label rendered by <BuildVersionTag /> and logged at boot.
// Precedence is deliberate:
//   1. GITHUB_SHA (CI/production) — short commit hash, set by deploy.yml.
//   2. `git describe` (local) — nearest tag plus drift info, e.g.
//      "0.5.0", "0.5.0-3-gabc1234", "0.5.0-3-gabc1234-dirty". This keeps the
//      local footer aligned with the GitHub release tag history automatically,
//      so versions can't silently drift from package.json again.
//   3. npm_package_version — for non-git builds (tarball, Docker without .git).
//   4. 'dev' — final fallback.
// The leading "v" from `git describe` (e.g. "v0.5.0") is stripped because
// <BuildVersionTag /> already prefixes "v" when rendering.
function resolveAppVersion(): string {
  const sha = process.env.GITHUB_SHA?.slice(0, 7)
  if (sha) return sha

  try {
    return execSync('git describe --tags --always --dirty', {
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim()
      .replace(/^v/, '')
  } catch {
    return process.env.npm_package_version || 'dev'
  }
}

export default defineConfig({
  base,
  // Build-time constant exposed to the app for the version footer + logging.
  // See resolveAppVersion() above for the precedence chain.
  define: {
    __APP_VERSION__: JSON.stringify(resolveAppVersion()),
  },
  // Bump build target so top-level await (used in src/net/room.ts to bind the
  // chosen Trystero strategy at module load) survives esbuild transpilation.
  // ES2022 is supported by Chrome 94+, Safari 15+, Firefox 93+ — all browsers
  // that also support the WebRTC features the app relies on.
  build: {
    target: 'es2022',
    // Vendor chunking. Without this, Vite/Rollup folds every static
    // dependency into a single ~520 KB monolith chunk that pushes past
    // the 500 KB warning and invalidates the whole vendor payload on
    // every app code change. Splitting by package family gives us:
    //   • better long-term HTTP caching (a React patch doesn't bust the
    //     yjs/i18n chunks),
    //   • smaller first paint when the user lands on `/` or `/dashboard`
    //     (yjs/qrcode/framer-motion only ship for the game routes that
    //     actually use them — combined with the React.lazy splits in
    //     App.tsx).
    //
    // Anything not listed here (trystero/* transports, dotlottie-react,
    // qrcode-when-dynamically-imported) is already auto-chunked by
    // Rollup at its dynamic-import boundary, so we keep the manual list
    // tight on purpose.
    rollupOptions: {
      output: {
        manualChunks: {
          'react-vendor': ['react', 'react-dom', 'react-router-dom'],
          'i18n-vendor': [
            'i18next',
            'i18next-browser-languagedetector',
            'react-i18next',
          ],
          'yjs-vendor': ['yjs', 'y-indexeddb'],
          'motion-vendor': ['framer-motion'],
          'qrcode-vendor': ['qrcode'],
        },
      },
    },
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // We register the SW ourselves from <PwaUpdateToast /> so we can show
      // an opt-in toast when a new version is waiting. Without this flag the
      // plugin would auto-inject a silent <script src="/registerSW.js">.
      injectRegister: false,
      includeAssets: [
        'favicon.svg',
        'manifest-icons/apple-touch-icon-180x180.png',
      ],
      manifest: {
        name: 'VucciriaGame',
        short_name: 'Vucciria',
        description: 'Multiplayer drinking board game — P2P, no backend.',
        theme_color: '#f59e0b',
        background_color: '#fef3c7',
        display: 'standalone',
        orientation: 'portrait',
        start_url: base,
        scope: base,
        // Icon set generated by @vite-pwa/assets-generator from
        // public/manifest-icons/source.svg. Regenerate with:
        //   npx @vite-pwa/assets-generator --preset minimal public/manifest-icons/source.svg
        // Paths are relative (no leading slash) so VitePWA prepends the
        // configured `base` automatically (e.g. /vucciria-game/ on GH Pages).
        icons: [
          {
            src: 'manifest-icons/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'manifest-icons/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: 'manifest-icons/maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Bundle locally-prefetched Noto Lottie JSON + SVGs into the precache.
        // `json` covers `public/noto/lottie/*.json`; `svg` already covers the
        // SVG variants. The `.wasm` glob covers the dotLottie WASM runtime.
        globPatterns: [
          '**/*.{js,css,html,svg,png,ico,webmanifest,json,wasm}',
        ],
        // New SW takes control of already-open pages as soon as it activates.
        // Combined with the explicit `updateSW(true)` triggered from the
        // <PwaUpdateToast /> "Refresh" button, this gives us a clean reload
        // path without forcing users out of an in-progress session.
        clientsClaim: true,
        // We deliberately keep `skipWaiting` off: the new SW sits in "waiting"
        // until the user accepts the update via the toast. Tapping "Refresh"
        // posts the SKIP_WAITING message and triggers `controllerchange`.
        skipWaiting: false,
        // Wipe Workbox precaches from previous builds so phones don't keep
        // gigabytes of stale Lottie JSON around after a few deploys.
        cleanupOutdatedCaches: true,
        // Per-asset budget bumped because some Noto Lottie JSON payloads are
        // ~200 KB and the default Workbox limit (2 MiB total) is comfortable
        // but the per-file warning trips at default ~2 MiB. Stay safe.
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
        runtimeCaching: [
          {
            // Long-tail avatar assets fetched on demand from Google's CDN.
            // StaleWhileRevalidate keeps mobile UX snappy: serve the cached
            // copy immediately, refresh in the background.
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/s\/e\/notoemoji\//,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'noto-emoji-cdn',
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
              },
              cacheableResponse: {
                statuses: [0, 200],
              },
            },
          },
        ],
      },
    }),
  ],
  server: {
    host: true,
    port: 5173,
  },
})
