export const GAME_NAMES_IT: readonly string[] = [
  "Ultimo giro prima della rissa",
  "La sbornia perfetta",
  "La vendetta del barista",
  "Colpi di shot",
  "Su e giù (ma giù è meglio)",
  "Fondo al bicchiere",
  "Birra o non birra",
  "Sbornia Collettiva",
  "La giostra dei cicchetti",
  "Sbronzati e Subisci",
  "Il valzer delle bottiglie",
  "Ubriachi ma contenti",
  "L'ora del bitter",
  "Brindisi e sberleffi",
  "Sorsi e rimorsi",
  "La battaglia dei bicchieri",
  "Tutti al bar!",
  "La notte dei folli",
  "Grappa e risate",
  "A tutto spritz",
  "Tira e molla (e bevi)",
  "Per un pugno di ghiaccio",
  "Cantina party",
  "Alticci e felici",
  "Alla salute della follia",
  "Sfida alcolica",
  "Vucciria Special",
  "Rum al tramonto",
  "Bevo ergo sum",
  "Spritz e patatina",
]
