export const GAME_NAMES_EN: readonly string[] = [
  "Last Call before Brawl",
  "The Hangover Prelude",
  "Bartender's Revenge",
  "Shots Fired",
  "The Tipsy Turvy",
  "Bottoms Up",
  "Sip Happens",
  "Beer Pressure",
  "Liquid Courage",
  "The Drunken Masters",
  "One Too Many",
  "Hiccup!",
  "The Booze Cruise",
  "Fermentation Celebration",
  "Mixology Mayhem",
  "Brew Ha Ha",
  "The Last Drop",
  "Cheers to Fear",
  "Panic at the Disco( Bar)",
  "Wobbly Pop",
  "Party Fouls",
  "Round After Round",
  "The Spritz Blitz",
  "Rumspringa",
  "Port and Whine",
  "Grappa Grappa Hey!",
  "Ale of the Storm",
  "Liver Let Die",
  "Spill the Beans (or Gin)",
  "Wine O'Clock Somewhere",
]
