/**
 * Auto-generated by `scripts/fetch-noto.mjs`. Do not edit by hand.
 *
 * Lists the Noto emoji codepoints (e.g. "1f98a") for which we have a local
 * copy of the asset under `public/noto/{lottie|svg}/{cp}.{json|svg}`.
 *
 * <NotoEmoji> uses these sets to decide whether to load from local (fast,
 * offline-safe) or from the CDN (long tail).
 */
export const LOCAL_LOTTIE_CODEPOINTS: readonly string[] = [
  '1f600',
  '1f60e',
  '1f973',
  '1f929',
  '1f607',
  '1f970',
  '1f60b',
  '1f913',
  '1f9d0',
  '1f920',
  '1f978',
  '1f608',
  '1f47b',
  '1f480',
  '1f916',
  '1f47d',
  '1f47e',
  '1f921',
  '1f479',
]

export const LOCAL_SVG_CODEPOINTS: readonly string[] = [
  '1f600',
  '1f60e',
  '1f973',
  '1f929',
  '1f607',
  '1f970',
  '1f60b',
  '1f913',
  '1f9d0',
  '1f920',
  '1f978',
  '1f608',
  '1f47b',
  '1f480',
  '1f916',
  '1f47d',
  '1f47e',
  '1f921',
  '1f479',
  '1f47a',
]
